/**
 * Created by nois on 9/6/17.
 */
export default {
  UPDATE_NETWORK_STATUS: 'UPDATE_NETWORK_STATUS',
  INIT_PENDING: 'INIT_PENDING',
  UPDATE_PENDING: 'UPDATE_PENDING',
  SET_LICENSE: 'SET_LICENSE'
}
